import { HomeStyle } from './styles'

import type { TNextPageWithLayout } from 'typescript/next.types'

import Head from 'next/head'

const Home: TNextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Home</title>

        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomeStyle>
        <span>Hello</span>
      </HomeStyle>
    </>
  )
}

export default Home
