import { useProducts } from './logic'
import { ProductsStyle } from './styles'

import type { TNextPageWithLayout } from 'typescript/next.types'

import Head from 'next/head'
import { AiOutlineSearch } from 'react-icons/ai'

const Products: TNextPageWithLayout = () => {
  const { onSearchClick, products, onSearchChange } = useProducts()

  return (
    <>
      <Head>
        <title>Products</title>

        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ProductsStyle>
        <form>
          <input
            type='text'
            name='search'
            aria-label='Pesquisar'
            placeholder='Pesquisar'
            onChange={onSearchChange}
          />

          <button
            type='button'
            data-cy='search'
            aria-label='Pesquisar'
            onClick={onSearchClick}
          >
            <AiOutlineSearch />
          </button>
        </form>

        {products && (
          <ul data-cy='products'>
            {products.map(product => (
              <li key={product.id}>{product.title}</li>
            ))}
          </ul>
        )}
      </ProductsStyle>
    </>
  )
}

export default Products
